export const cats = [
  {
    id: "rocket-tabby",
    title: "공중부양에 성공한 김치즈",
    caption: "장난감을 향한 집념이 중력을 이겼습니다.",
    sticker: "중력 무시 중",
    image: "/cats/rocket-tabby.webp",
    alt: "거실에서 장난감을 향해 두 발로 뛰어오른 주황색 줄무늬 고양이",
  },
  {
    id: "cucumber-shock",
    title: "오이를 목격한 백설기",
    caption: "평화로운 아침은 오이 하나로 끝났습니다.",
    sticker: "충격 200%",
    image: "/cats/cucumber-shock.webp",
    alt: "노란색 주방에서 오이를 보고 두 발로 선 흰색 고양이",
  },
  {
    id: "confetti-sprint",
    title: "파티를 접수한 밤콩이",
    caption: "목적지는 모르지만 일단 전속력입니다.",
    sticker: "브레이크 고장",
    image: "/cats/confetti-sprint.webp",
    alt: "파란 바닥 위 색종이 조각 사이를 달리는 검은 고양이",
  },
  {
    id: "box-overflow",
    title: "택배를 사칭한 왕만두",
    caption: "상자는 작지 않습니다. 고양이가 클 뿐입니다.",
    sticker: "반품 불가",
    image: "/cats/box-overflow.webp",
    alt: "작은 종이 상자에 몸을 넣고 네 발을 내민 회색 줄무늬 고양이",
  },
  {
    id: "laundry-launch",
    title: "빨래에서 출몰한 삼색이",
    caption: "양말 한 짝과 평온이 동시에 사라졌습니다.",
    sticker: "세탁 금지",
    image: "/cats/laundry-launch.webp",
    alt: "양말이 날리는 세탁실에서 빨래 바구니 밖으로 뛰어오른 삼색 고양이",
  },
  {
    id: "megaphone-tuxedo",
    title: "볼륨 조절 없는 턱시도",
    caption: "아침밥이 3분 늦었다는 공식 입장입니다.",
    sticker: "민원 접수 중",
    image: "/cats/megaphone-tuxedo.webp",
    alt: "카메라 가까이에서 입을 벌리고 크게 우는 검정과 흰색 턱시도 고양이",
  },
  {
    id: "food-cover-bandit",
    title: "반찬 뚜껑에 잠복한 순두부",
    caption: "숨은 게 아니라 신선하게 보관되는 중입니다.",
    sticker: "밀폐 실패",
    image: "/cats/food-cover-bandit.webp",
    alt: "주방 조리대 위 투명한 음식 덮개 안에서 놀란 표정으로 돌아보는 크림색 고양이",
  },
  {
    id: "piano-panther",
    title: "독주회를 강행한 깜장이",
    caption: "악보는 없지만 자신감은 포르티시모입니다.",
    sticker: "앙코르 금지",
    image: "/cats/piano-panther.webp",
    alt: "거실의 피아노 건반 위에 두 앞발을 올리고 진지하게 바라보는 검은 고양이",
  },
  {
    id: "toilet-paper-sprint",
    title: "화장지를 정복한 치토스",
    caption: "두루마리 하나로 집 전체에 길을 만들었습니다.",
    sticker: "휴지 전멸",
    image: "/cats/toilet-paper-sprint.webp",
    alt: "화장지를 몸에 두른 채 욕실 바닥을 힘차게 달려오는 주황색 줄무늬 고양이",
  },
  {
    id: "robot-vacuum-captain",
    title: "로봇청소기를 접수한 회장님",
    caption: "청소는 기계가 하고 지휘는 고양이가 합니다.",
    sticker: "자동 운전 중",
    image: "/cats/robot-vacuum-captain.webp",
    alt: "빨간 망토를 두르고 로봇청소기 위에서 한쪽 앞발을 든 회색 고양이",
  },
  {
    id: "curtain-climber",
    title: "커튼 정상에 오른 카오스",
    caption: "올라갈 계획만 있었고 내려올 계획은 없었습니다.",
    sticker: "등반 성공",
    image: "/cats/curtain-climber.webp",
    alt: "햇빛 드는 거실에서 커튼 꼭대기까지 기어올라 아래를 보는 삼색 고양이",
  },
  {
    id: "fridge-bandit",
    title: "야식 현행범 턱시도",
    caption: "치즈가 먼저 눈을 마주쳤다는 진술입니다.",
    sticker: "증거 확보",
    image: "/cats/fridge-bandit.webp",
    alt: "밤의 주방에서 열린 냉장고 속 치즈에 앞발을 뻗으며 카메라를 보는 턱시도 고양이",
  },
  {
    id: "printer-overlord",
    title: "복합기를 지배한 설탕이",
    caption: "오늘 출력물은 전부 고양이 결재를 거칩니다.",
    sticker: "용지 부족",
    image: "/cats/printer-overlord.webp",
    alt: "종이가 흩날리는 홈 오피스에서 프린터 위에 당당히 앉은 흰색 장모 고양이",
  },
  {
    id: "plant-pot-kitten",
    title: "분갈이를 독학한 아기호두",
    caption: "화분은 비웠고 본인은 아주 잘 심었습니다.",
    sticker: "새싹 대기 중",
    image: "/cats/plant-pot-kitten.webp",
    alt: "흙이 흩어진 실내 정원에서 커다란 테라코타 화분 안에 들어간 아기 줄무늬 고양이",
  },
  {
    id: "faucet-fighter",
    title: "수도꼭지와 결투 중인 은단이",
    caption: "물을 잡을 수 없다는 사실을 아직 인정하지 않았습니다.",
    sticker: "재대결 신청",
    image: "/cats/faucet-fighter.webp",
    alt: "욕실 세면대 안에서 수도꼭지 물줄기를 앞발로 잡으려는 은색 줄무늬 고양이",
  },
  {
    id: "shoe-avalanche",
    title: "신발장을 폭파한 크림빵",
    caption: "신발은 무너졌지만 탐험대장은 무사합니다.",
    sticker: "구조 거부",
    image: "/cats/shoe-avalanche.webp",
    alt: "현관의 쏟아진 신발 더미 한가운데서 두 앞발을 들고 있는 주황색과 흰색 장모 고양이",
  },
];
