const coupangSearchUrl = (query) =>
  `https://www.coupang.com/np/search?q=${encodeURIComponent(query)}`;

export const snackFilters = [
  { id: "all", label: "전체 간식" },
  { id: "hydration", label: "수분 충전" },
  { id: "dental", label: "치아 관리" },
  { id: "reward", label: "보상 간식" },
  { id: "simple", label: "원물 간식" },
];

export const snacks = [
  {
    id: "ciao-churu-variety",
    name: "챠오츄르 구루메 버라이어티 60P",
    maker: "이나바",
    type: "촉촉한 스틱",
    description: "참치·가다랑어·닭가슴살을 번갈아 급여하기 좋은 대용량 혼합 구성입니다.",
    reason: "입맛을 찾는 고양이의 첫 간식 후보",
    filters: ["hydration", "reward"],
    tone: "orange",
    searchUrl: coupangSearchUrl("챠오츄르 고양이 구루메 버라이어티 60p"),
  },
  {
    id: "sheba-soup",
    name: "쉬바 수제 수프 혼합맛 12개",
    maker: "쉬바",
    type: "수프 파우치",
    description: "참치와 닭가슴살 베이스의 국물 타입으로 음수량이 아쉬운 날 곁들이기 좋습니다.",
    reason: "물그릇을 외면하는 까다로운 냥이에게",
    filters: ["hydration"],
    tone: "blue",
    searchUrl: coupangSearchUrl("쉬바 고양이 수제 수프 혼합맛 40g 12개"),
  },
  {
    id: "greenies-dental-salmon",
    name: "필라인 그리니즈 덴탈 스낵 연어 130g",
    maker: "그리니즈",
    type: "덴탈 크런치",
    description: "바삭한 식감을 좋아하는 성묘를 위한 덴탈 타입 간식입니다.",
    reason: "씹는 간식을 좋아하는 성묘의 보상용",
    filters: ["dental", "reward"],
    tone: "mint",
    searchUrl: coupangSearchUrl("그리니즈 고양이 필라인 덴탈 스낵 연어 130g"),
  },
  {
    id: "temptations-chicken",
    name: "템테이션 고양이 스낵 닭고기맛 75g",
    maker: "템테이션",
    type: "바삭 스낵",
    description: "한 알씩 나눠주기 편해 놀이 후 보상이나 노즈워크에 활용하기 좋습니다.",
    reason: "간식 봉지만 들어도 달려오는 냥이에게",
    filters: ["reward"],
    tone: "yellow",
    searchUrl: coupangSearchUrl("템테이션 고양이 스낵 맛있는 닭고기맛 75g"),
  },
  {
    id: "naturepet-pollock",
    name: "네이처펫 동결건조 북어 트릿 140g",
    maker: "네이처펫",
    type: "동결건조",
    description: "손으로 작게 나누거나 물에 불려 급여할 수 있는 북어 타입 트릿입니다.",
    reason: "바삭한 원물 향을 좋아하는 고양이에게",
    filters: ["simple", "reward"],
    tone: "violet",
    searchUrl: coupangSearchUrl("네이처펫 반려동물 동결건조 북어 트릿 140g"),
  },
  {
    id: "thecats-soup-pouch",
    name: "더캣츠 스프 파우치 혼합맛 20개",
    maker: "더캣츠",
    type: "스프 파우치",
    description: "치킨과 연어 맛을 넉넉하게 구비해 수분 보충용 토핑으로 활용하기 좋은 구성입니다.",
    reason: "여러 마리와 함께 사는 다묘 가정에",
    filters: ["hydration"],
    tone: "pink",
    searchUrl: coupangSearchUrl("더캣츠 고양이 스프 파우치 혼합맛 치킨 연어 50g 20개"),
  },
];
